# Generated by Django 5.0.1 on 2024-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(max_length=20),
        ),
    ]
