# Generated by Django 5.0.1 on 2024-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='type',
            field=models.CharField(choices=[('one_book', 'One Book'), ('several_books', 'Several Books')], default='one_book', max_length=20),
        ),
    ]
