# Generated by Django 5.0.1 on 2024-03-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(choices=[('one_book', 'One Book'), ('several_books', 'Several Books'), ('library', 'Library'), ('wish_list', 'Wish List')], default='one_book', max_length=20),
        ),
    ]
