# Generated by Django 5.0.1 on 2024-05-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_customgroup_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='places',
        ),
    ]
