# Generated by Django 5.0.1 on 2024-03-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_customgroup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customgroup',
            old_name='type',
            new_name='group_type',
        ),
    ]
