# Generated by Django 5.0.1 on 2024-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_customgroup_slug_alter_customgroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='kname',
            field=models.CharField(default='new_group', max_length=50),
            preserve_default=False,
        ),
    ]
