# Generated by Django 5.0.1 on 2024-04-09 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_customgroup_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
