# Generated by Django 5.0.1 on 2024-03-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_customgroup_kname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
