# Generated by Django 5.0.1 on 2024-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_customgroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='group_type',
            field=models.CharField(choices=[('one_book', 'One Book'), ('several_books', 'Several Books'), ('library', 'Library'), ('wishlist', 'Wish List')], default='one_book', max_length=20),
        ),
    ]
