# Generated by Django 5.0.1 on 2024-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='books', to='groups.customgroup'),
        ),
    ]
