# Generated by Django 5.0.1 on 2024-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='need_return_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
