# Generated by Django 5.0.1 on 2024-05-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombook',
            name='places',
        ),
        migrations.RemoveField(
            model_name='custombook',
            name='tags',
        ),
    ]
