# Generated by Django 5.0.1 on 2024-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='custom_borrower',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
