# Generated by Django 5.0.1 on 2024-04-19 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow_custom_borrower_alter_borrow_borrow_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow', to=settings.AUTH_USER_MODEL),
        ),
    ]
