# Generated by Django 5.0.1 on 2024-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_custombook_places_remove_custombook_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombook',
            name='is_disponible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
