# Generated by Django 5.0.1 on 2024-03-27 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_library',
            field=models.ManyToManyField(blank=True, related_name='in_libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='in_wishlist',
            field=models.ManyToManyField(blank=True, related_name='in_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
