# Generated by Django 5.0.1 on 2024-05-03 09:24

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow_need_return_confirmation'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='need_borrow_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custombook',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_citations', to=settings.AUTH_USER_MODEL)),
                ('kbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='books.custombook')),
            ],
        ),
    ]
