# Generated by Django 5.0.1 on 2024-03-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_day',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_hour',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
