# Generated by Django 5.0.1 on 2024-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_genre_booktag_book_genres_delete_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='books.genre'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='kbook',
            field=models.ManyToManyField(blank=True, related_name='kbook_tags', to='books.custombook'),
        ),
    ]
