# Generated by Django 5.0.1 on 2024-04-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_custombook_author_custombook_cover_and_more'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombook',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kbook_group', to='groups.customgroup'),
        ),
    ]
