# Generated by Django 5.0.1 on 2024-05-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_genres_alter_booktag_kbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktag',
            old_name='kbook',
            new_name='kbooks',
        ),
    ]
