# Generated by Django 5.0.1 on 2024-04-09 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_meeting_meeting_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading', 'Currently reading'), ('wish_to_read', 'Wish to read'), ('no_read', 'No read'), ('no_read', "Won't read"), ('give_up', 'Give up')], default='no_read', max_length=32),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrow',
            name='demand_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='late_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for confirmation'), ('no_response', "Owner didn't give a response"), ('confirmed', 'Confirmed'), ('rejected', 'Cancelled by owner'), ('cancelled', 'Cancelled by requester'), ('no_show', 'Delivery  did not take place'), ('on_going', 'Product actually borrowed by requester '), ('returned', 'Product returned by the borrower'), ('late_return', 'Return did not take place on time'), ('no_return', 'Object not returned')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='CustomBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_origin', to='books.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='custom_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to='books.custombook'),
        ),
    ]
