# Generated by Django 5.0.1 on 2024-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_in_library_book_in_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
