# Generated by Django 5.0.1 on 2024-04-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_owner_book_status_borrow_borrow_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading now', 'Reading Now'), ('wish_to_read', 'Wish to read'), ('no_read', 'No read'), ('no_read', "Won't read"), ('give_up', 'Give up')], default='no_read', max_length=32),
        ),
    ]
