# Generated by Django 5.0.1 on 2024-03-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_meeting_place'),
        ('groups', '0006_alter_customgroup_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup'),
            preserve_default=False,
        ),
    ]
