# Generated by Django 5.0.1 on 2024-04-12 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_custombook_admin'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombook',
            name='group',
        ),
        migrations.AddField(
            model_name='custombook',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='kbook_group', to='groups.customgroup'),
        ),
        migrations.AlterField(
            model_name='custombook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kbook', to='books.book'),
        ),
    ]
