# Generated by Django 5.0.1 on 2024-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_kbook_booktag_kbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombook',
            name='kowner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
