# Generated by Django 5.0.1 on 2024-03-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_meeting_group'),
        ('groups', '0006_alter_customgroup_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='books.book'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.customgroup'),
        ),
    ]
