# Generated by Django 5.0.1 on 2024-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
