# Generated by Django 5.0.1 on 2024-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_custombook_groups'),
        ('groups', '0003_alter_customgroup_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombook',
            name='groups',
        ),
        migrations.AddField(
            model_name='custombook',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_book', to='groups.customgroup'),
        ),
    ]
