# Generated by Django 5.0.1 on 2025-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_custombook_kowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
