# Generated by Django 5.0.1 on 2024-04-11 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='give_up',
            field=models.ManyToManyField(blank=True, related_name='give_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='no_read',
            field=models.ManyToManyField(blank=True, related_name='no_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='readings',
            field=models.ManyToManyField(blank=True, related_name='readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='wont_read',
            field=models.ManyToManyField(blank=True, related_name='wont_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
