# Generated by Django 5.0.1 on 2024-04-18 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_custombook_reservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
